language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost1.50-all-dev
    - sudo apt-get install libatlas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install cmake
    - sudo apt-get install git
    - git clone https://github.com/hrhill/numeric-bindings.git
    - sudo cp -r numeric-bindings/boost/numeric/bindings /usr/include/boost/numeric
script:
    - cmake -DCMAKE_BUILD_TYPE=Release . && make && make test

