language: cpp
compiler:
    - clang
    - gcc

# Setup different environments to test
env:
    - CPP14=0
    - CPP14=1

before_install:
    # Setup repos etc before installation
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ "$CXX" == "clang++" -a "$CPP14" == "1" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq

# Install dependencies
install:
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" == "clang++"]; then CXX=g++-4.8; fi
    - if [ "$CXX" == "clang++"]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
    - if [ "$CXX" == "clang++"]; then CXX=clang++-3.4; fi

    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libopenblas-dev
    - sudo apt-get install -qq cmake

script:
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test

