language: cpp
compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq

before_install:
    - sudo apt-get update -qq

# Install dependencies
install:
    - sudo apt-get install -qq cmake
    - sudo apt-get install -qq libopenblas-dev
    - sudo apt-get install -qq libboost-dev

script:
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make
    - make test

